// build-check.mjs — offline build validation for Market Intelligence (Phase 1).
//
// The app is vanilla ES modules with no bundler by design (see README.md), so
// there is nothing to compile. "npm run build" therefore validates that every
// top-level .js module parses as a valid ES module, so a broken file (syntax
// error, stray brace, corrupted edit) fails the build instead of only breaking
// at runtime in the browser.
//
// Approach: spawn `node --check` per module. This is syntax-only and never
// executes the module, so browser-only globals (document, window,
// localStorage) and CDN-loading code in the UI modules cannot false-fail the
// check, and the app's behavior is untouched.
//
// Run:  node build-check.mjs   (or: npm run build)

import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import { existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const ROOT = fileURLToPath(new URL('.', import.meta.url));

// Every top-level .js module the app ships. Explicit list keeps the check
// deterministic and independent of unrelated stray files in the repo.
const MODULES = [
  'app.js',
  'api.js',
  'ai-engine.js',
  'assets.js',
  'alerts.js',
  'charts.js',
  'config.js',
  'indicators.js',
  'market-data.js',
  'secure-store.js',
  'Marketanalysis.js',
  'notifications.js',
  'pattern-engine.js',
  'prediction-engine.js',
  'storage.js',
  'utils.js',
];

let failures = 0;

console.log('build-check: validating top-level ES modules with `node --check`');

for (const mod of MODULES) {
  const file = path.join(ROOT, mod);
  if (!existsSync(file)) {
    console.error(`  ✗ ${mod} — MISSING (expected at ${file})`);
    failures += 1;
    continue;
  }
  try {
    execFileSync(process.execPath, ['--check', file], {
      stdio: 'pipe',
      encoding: 'utf8',
    });
    console.log(`  ✓ ${mod} — syntax OK`);
  } catch (err) {
    console.error(`  ✗ ${mod} — syntax error`);
    console.error(String(err.stderr || err.message).trim());
    failures += 1;
  }
}

if (failures > 0) {
  console.error(`\nBUILD FAILED — ${failures} module(s) failed to parse`);
  process.exit(1);
}

// ---------------------------------------------------------------------------
// Generate build-info.js (git short hash) and mirror web sources into www/.
//
// The app is vanilla ES modules with no bundler, so "shipping" means copying
// the top-level web sources into www/ (Capacitor's webDir) verbatim. Doing
// that here makes `npm run build` the single command that refreshes www/ with
// the CURRENT source before `npx cap sync android` copies it into the APK.

const WEB_FILES = [...MODULES, 'index.html', 'style.css'];
const WWW = path.join(ROOT, 'www');

let commit = 'unknown';
try {
  commit = execFileSync('git', ['rev-parse', '--short', 'HEAD'], {
    cwd: ROOT, stdio: 'pipe', encoding: 'utf8',
  }).trim();
} catch (err) {
  console.warn('build-check: could not read git hash — build-info.js will say "unknown"');
}
const builtAt = new Date().toISOString();
const buildInfoSrc =
  `// GENERATED by build-check.mjs at build time — do not edit by hand.\n` +
  `export const BUILD_INFO = { commit: ${JSON.stringify(commit)}, builtAt: ${JSON.stringify(builtAt)} };
`;
for (const dir of [ROOT, WWW]) {
  fs.writeFileSync(path.join(dir, 'build-info.js'), buildInfoSrc);
}
console.log(`build-info: commit ${commit} (${builtAt}) written to ./ and ./www/`);

fs.mkdirSync(WWW, { recursive: true });
for (const f of WEB_FILES) {
  fs.copyFileSync(path.join(ROOT, f), path.join(WWW, f));
}
console.log(`www-sync: copied ${WEB_FILES.length} files into www/`);

console.log(`\nBUILD PASS — all ${MODULES.length} modules parse as valid ES modules`);
process.exit(0);