#!/usr/bin/env -S uv run
# /// script
# dependencies = ["pydantic", "python-dotenv", "pyyaml"]
# ///
"""ADW Polish — generated by make_adw.

Usage:
    uv run adws/adw_polish.py "<prompt or path/to/prompt.md>" [--config adws/adw_sssf_config/sssf.config.yaml] [--adw-id a1b2c3d4]

Phases: engineer(request) -> game-feel-tuner -> sound-designer -> vfx-engineer -> qa-engineer
"""

import argparse
import sys

from adw_modules import agents, gates, session, utils
from adw_modules.data_types import AgentCall, PhaseParams, AudioOutput, FeelOutput, QAReportOutput, VFXOutput

REQUIRED_AGENTS = ['game-feel-tuner', 'qa-engineer', 'sound-designer', 'vfx-engineer']


def main(prompt: str, config: str = "adws/adw_sssf_config/sssf.config.yaml", adw_id: str | None = None) -> int:
    cfg = agents.load_config(config)
    agents.validate(cfg, REQUIRED_AGENTS)
    run = session.ensure(cfg, adw_id)

    with run.phase(PhaseParams(name="request", kind="engineer", owner=run.engineer,
                               description="Capture the incoming ask")) as ph:
        ph.log(input=prompt)

    previous = None
    with run.phase(PhaseParams(name="game-feel-tuner", kind="agent", owner="game-feel-tuner",
                               description="Add and tune game feel: juice, tweens, screenshake, feedback")) as ph:
        previous = ph.call(AgentCall(output_type=FeelOutput, prompt=prompt,
                                     previous=previous,
                                     gates=[gates.artifacts_exist]))

    with run.phase(PhaseParams(name="sound-designer", kind="agent", owner="sound-designer",
                               description="Wire and balance audio cues and music; verify the mute toggle")) as ph:
        previous = ph.call(AgentCall(output_type=AudioOutput, prompt=prompt,
                                     previous=previous,
                                     gates=[gates.artifacts_exist]))

    with run.phase(PhaseParams(name="vfx-engineer", kind="agent", owner="vfx-engineer",
                               description="Create and tune visual effects (shaders, particles, post-fx)")) as ph:
        previous = ph.call(AgentCall(output_type=VFXOutput, prompt=prompt,
                                     previous=previous,
                                     gates=[gates.artifacts_exist]))

    with run.phase(PhaseParams(name="qa-engineer", kind="agent", owner="qa-engineer",
                               description="Run a structured QA pass and report bugs with severity")) as ph:
        previous = ph.call(AgentCall(output_type=QAReportOutput, prompt=prompt,
                                     previous=previous,
                                     gates=[gates.artifacts_exist]))

    return 0 if run.succeeded else 1


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("prompt", help="inline text or a path to a prompt file")
    parser.add_argument("--config", default="adws/adw_sssf_config/sssf.config.yaml")
    parser.add_argument("--adw-id", default=None, help="join or pin an existing session")
    args = parser.parse_args()
    sys.exit(main(utils.resolve_prompt(args.prompt), args.config, args.adw_id))
